accumulate_grad_batches: 1
amp: false
aux_l1_loss: true
aux_percep_loss: false
aux_ssim_loss: false
base_config:
- ./diffsr_base.yaml
- ./df2k4x.yaml
batch_size: 64
beta_end: 0.02
beta_s: 0.008
beta_schedule: cosine
binary_data_dir: data/binary/df2k4x
blur_kernel: iso_gaussian
blur_type: iso_gaussian
check_val_every_n_epoch: 10
clip_grad_norm: 10
clip_input: true
crop_size: 320
data_augmentation: false
data_interp: bicubic
debug: false
decay_steps: 200000
denoise_fn: unet
ds_workers: 1
endless: false
eval_batch_size: 1
fix_rrdb: true
gen_dir_name: ''
gn_groups: 0
hidden_size: 64
infer: false
kernel_size: 21
lambda_max: 4.0
lambda_min: 0.2
load_ckpt: ''
loss_type: l1
lr: 0.0002
max_epochs: 1000
max_updates: 400000
noise: 0.0
num_ckpt_keep: 100
num_sanity_val_steps: 4
num_workers: 8
patch_size: 160
pred_noise: true
print_arch: false
print_nan_grads: false
res: true
res_rescale: 2.0
resume_from_checkpoint: 0
rrdb_ckpt: checkpoints/rrdb_div2k_1
rrdb_num_block: 8
rrdb_num_feat: 32
save_best: true
save_codes:
- configs
- models
- tasks
- utils
save_intermediate: false
scale: 4
seed: 1234
show_training_process: false
sig_max: 0.2
sig_min: 2.6
sr_scale: 4
style_interp: false
tb_log_interval: 100
test_batch_size: 1
test_crop_size:
- 2040
- 2040
test_hr: /home/vipsl416-4-zhangliz/Datasets/DIV2K/DIV2K_valid_HR_mod/*.png
test_input_dir: ''
test_lr: /home/vipsl416-4-zhangliz/Datasets/DIV2K/DIV2K_valid_LR_bicubic/X4/*.png
test_save_png: false
test_thresh_size: 0
thresh_size: 160
timesteps: 100
train_hr: /home/vipsl416-4-zhanglize/Datasets/DIV2K/DIV2K_train_HR/*.png
trainer_cls: tasks.srdiff_gt.SRDiffIxi
unet_dim_mults: 1|2|3|4
up_input: false
use_attn: false
use_rrdb: true
use_wn: false
val_check_interval: 4000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_steps: 4
weight_init: false
work_dir: checkpoints/diffsr_div2k_1
